name: CI Pipeline

on:
  push:
    branches:
      - '**'  # Executar a pipeline em qualquer branch quando houver um push
  pull_request:
    branches:
      - branchdeteste

jobs:
  test:
    runs-on: ubuntu-latest  # Executa em um ambiente Ubuntu

    strategy:
      matrix:
        node-version: "20.x"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Faz o checkout do código do repositório para ver se está tudo certo, ehehe

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install  # Instala as dependências do projeto

      - name: Run tests
        run: npm test  # Executa os testes configurados (neste caso, Jest)


